const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// DAILY CLASS ATTENDANCE RECORD
// Automatically generated summary for each class each day
const dailyClassAttendanceSchema = new Schema(
  {
    class: {
      type: Schema.Types.ObjectId,
      ref: 'Class',
      required: true,
      index: true,
    },
    date: {
      type: Date,
      required: true,
      index: true,
    },
    // Present students list
    presentStudents: [
      {
        student: {
          type: Schema.Types.ObjectId,
          ref: 'Student',
        },
        entryTime: Date,
        exitTime: Date,
      },
    ],
    // Absent students list
    absentStudents: [
      {
        student: {
          type: Schema.Types.ObjectId,
          ref: 'Student',
        },
      },
    ],
    // Late arrivals
    lateStudents: [
      {
        student: {
          type: Schema.Types.ObjectId,
          ref: 'Student',
        },
        entryTime: Date,
        minutesLate: Number,
      },
    ],
    // Early departures
    earlyLeaveStudents: [
      {
        student: {
          type: Schema.Types.ObjectId,
          ref: 'Student',
        },
        exitTime: Date,
        reason: String,
      },
    ],
    // Statistics
    totalStudents: {
      type: Number,
      default: 0,
    },
    presentCount: {
      type: Number,
      default: 0,
    },
    absentCount: {
      type: Number,
      default: 0,
    },
    lateCount: {
      type: Number,
      default: 0,
    },
    attendanceRate: {
      type: Number, // Percentage
      default: 0,
    },
    // Automation tracking
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
    lastUpdated: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

// Prevent duplicate records for same class on same date
dailyClassAttendanceSchema.index({ class: 1, date: 1 }, { unique: true });

// Indexes for queries
dailyClassAttendanceSchema.index({ date: -1 });
dailyClassAttendanceSchema.index({ attendanceRate: 1 });

// Pre-save middleware to calculate statistics
dailyClassAttendanceSchema.pre('save', function (next) {
  this.presentCount = this.presentStudents.length;
  this.absentCount = this.absentStudents.length;
  this.lateCount = this.lateStudents.length;

  if (this.totalStudents > 0) {
    this.attendanceRate =
      Math.round((this.presentCount / this.totalStudents) * 100 * 100) / 100;
  }

  this.lastUpdated = new Date();
  next();
});

const DailyClassAttendance = mongoose.model(
  'DailyClassAttendance',
  dailyClassAttendanceSchema
);

module.exports = DailyClassAttendance;
